export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";


export const DELETE_START = "LOGIN_START";
export const DELETE_SUCCESS = "LOGIN_SUCCESS";
export const DELETE_FAIL = "LOGIN_FAIL";

export const UPDATE_SUCCESS = "UPDATE_SUCCESS";